---
version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  ignore:
    - dependency-name: "github.com/paketo-buildpacks/packit/v2"
    - dependency-name: "github.com/cenkalti/backoff/v4"
    - dependency-name: "github.com/cloudflare/circl"
    - dependency-name: "github.com/cyphar/filepath-securejoin"

  allow:
  # Allow both direct and indirect updates for all packages
  - dependency-type: "all"
  # group all minor and patch dependency updates together
  groups:
    go-modules:
      patterns:
      - "*"
      update-types:
      - "minor"
      - "patch"
      exclude-patterns:
      - "github.com/anchore/stereoscope"
      - "github.com/testcontainers/testcontainers-go"
      - "github.com/docker/docker"
      - "github.com/containerd/containerd"
